#!/usr/bin/env python3
"""
gen_html_header.py  —  compress index.html and generate webdisplay_html.h
Run: python3 gen_html_header.py
"""
import os, gzip, sys

html_path = os.path.join(os.path.dirname(__file__), '..', 'html', 'index.html')
out_path  = os.path.join(os.path.dirname(__file__), 'webdisplay_html.h')

with open(html_path, 'rb') as f:
    raw = f.read()

# Write uncompressed version as C array
arr = ', '.join(f'0x{b:02x}' for b in raw)
out = f"""/* Auto-generated by gen_html_header.py — DO NOT EDIT */
#pragma once
#include <stddef.h>
static const uint8_t wd_html[] = {{
{arr}
}};
static const size_t wd_html_len = {len(raw)};
"""
with open(out_path, 'w') as f:
    f.write(out)

print(f"Generated {out_path}  ({len(raw)} bytes)")
