#!/usr/bin/env python3
"""
gen_html_header.py  —  embed index.html as a C header (no gzip)
Run: python3 gen_html_header.py

NOTE: gzip is intentionally NOT used here.
Firefox (and some embedded HTTP clients) will reject a gzip response if:
  - The request didn't include Accept-Encoding: gzip, OR
  - The Content-Encoding header is present but the client didn't negotiate it.
Serving plain HTML avoids all encoding negotiation and is safe for ~17KB files.
"""
import os

html_path = os.path.join(os.path.dirname(__file__), '..', 'html', 'index.html')
out_path  = os.path.join(os.path.dirname(__file__), 'webdisplay_html.h')

with open(html_path, 'rb') as f:
    raw = f.read()

arr = ', '.join(f'0x{b:02x}' for b in raw)
out = f"""/* Auto-generated by gen_html_header.py — DO NOT EDIT */
#pragma once
#include <stddef.h>
static const uint8_t wd_html[] = {{
{arr}
}};
static const size_t wd_html_len = {len(raw)};
/* NOTE: plain HTML, not gzip-compressed.
 * The C server must NOT send Content-Encoding: gzip for this data. */
"""

with open(out_path, 'w') as f:
    f.write(out)

print(f"Generated {out_path}  ({len(raw)} bytes, plain HTML)")